debug: false
httpport: 19010
grpcport: 19011
oauth2:
  type: "github" #Oauth2 登录接入类型，gitee/github
  admin: "random11235813" #管理员列表，填写Github昵称，多个用英文逗号隔开
  clientid: "Ov23lixhhckt3qD2cSs7" # Clientid
  clientsecret: "0170dd9fc72355370250351d1975d2abd7f260f1" #Secret
site:
  brand: "私人专属" #站点名称
  cookiename: "nezha-dashboard" #浏览器 Cookie 字段名，可不改
  theme: "default" #主题
