global:
# 抓取间隔，60秒向目标抓取一次数据
  scrape_interval: 60s
  evaluation_interval: 60s

# 这里表示抓取对象的配置
scrape_configs:
  - job_name: 'prometheus'
  # 重写了全局抓取间隔时间，由60秒重写成30秒
    scrape_interval: 30s
    static_configs:
      - targets: ['192.168.31.51:9090']
  - job_name: 'linux'
    static_configs:
      - targets: ['192.168.31.51:9100']
